import {createDocument,createPage,createFrame,normalizeDocument,touch,cloneDocument} from './document-model.js';
import {renderDocument} from './render.js';
import {selection,selectPage,selectFrame,selectCell,selectedPage,selectedFrame} from './selection.js';
import {saveDocument,loadDocument,listDocuments} from './storage.js';

let doc=normalizeDocument(JSON.parse(localStorage.getItem('rechnung3.lastDocument')||'null')||createDocument());selection.pageId=doc.pages[0].id;let drag=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function refresh(){renderDocument(doc,selection);renderPages();syncPalettes();localStorage.setItem('rechnung3.lastDocument',JSON.stringify(doc));$('#saveStatus').textContent='Unsaved';}
function changed(){touch(doc);refresh();}
function renderPages(){const list=$('#pageList');list.innerHTML='';doc.pages.forEach((p,i)=>{const b=document.createElement('button');b.className='page-thumb'+(selection.pageId===p.id?' is-selected':'');b.draggable=true;b.textContent=`${i+1}. ${p.name||'Page'}`;b.onclick=()=>{selectPage(p.id);refresh();};b.ondragstart=e=>e.dataTransfer.setData('text/plain',p.id);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{const from=e.dataTransfer.getData('text/plain');const old=doc.pages.findIndex(x=>x.id===from);const page=doc.pages.splice(old,1)[0];doc.pages.splice(i,0,page);doc.pages.forEach((x,n)=>x.order=n);changed();};list.append(b);});const docs=$('#documentList');docs.innerHTML='<option value="">Saved documents…</option>'+listDocuments().map(x=>`<option value="${x.id}">${x.title}</option>`).join('');}
function syncPalettes(){const f=selectedFrame(doc);$$('[data-transform]').forEach(i=>{const k=i.dataset.transform;if(!f){i.value='';return}if(i.type==='checkbox')i.checked=!!f[k];else i.value=f[k]??'';});$$('[data-type-style]').forEach(i=>{i.disabled=!f||f.type!=='text';if(f?.type==='text')i.value=f.style[i.dataset.typeStyle]??'';});const cell=selection.cell;$('#cellRef').textContent=cell?`${String.fromCharCode(65+cell.col)}${cell.row+1}`:'—';const tf=f?.type==='table'?f:null;$('#cellInput').disabled=!cell||!tf;$('#cellInput').value=cell&&tf?(tf.content.rows[cell.row]?.cells[cell.col]?.formula||tf.content.rows[cell.row]?.cells[cell.col]?.value||''):'';$('#discountType').value=tf?.content.discount?.type||'none';$('#discountValue').value=tf?.content.discount?.value||0;$('#carryLabel').value=tf?.content.carryLabel||'Subtotal carried forward';}
function mmFromPx(px){return px*25.4/96;}
$('#documentCanvas').addEventListener('mousedown',e=>{const frame=e.target.closest('.frame');const page=e.target.closest('.page');if(page&&!frame){selectPage(page.dataset.pageId);refresh();return}if(!frame)return;selectFrame(frame.dataset.pageId,frame.dataset.frameId);const f=selectedFrame(doc);if(e.target.classList.contains('resize-handle'))drag={kind:'resize',f,startX:e.clientX,startY:e.clientY,w:f.width,h:f.height};else if(!f.locked&&!e.target.closest('td')&&!frame.isContentEditable)drag={kind:'move',f,startX:e.clientX,startY:e.clientY,x:f.x,y:f.y};refresh();});
window.addEventListener('mousemove',e=>{if(!drag)return;const dx=mmFromPx(e.clientX-drag.startX),dy=mmFromPx(e.clientY-drag.startY);if(drag.kind==='move'){drag.f.x=Math.max(0,+(drag.x+dx).toFixed(1));drag.f.y=Math.max(0,+(drag.y+dy).toFixed(1));}else{drag.f.width=Math.max(5,+(drag.w+dx).toFixed(1));drag.f.height=Math.max(5,+(drag.h+dy).toFixed(1));}renderDocument(doc,selection);syncPalettes();});
window.addEventListener('mouseup',()=>{if(drag){drag=null;changed();}});
$('#documentCanvas').addEventListener('click',e=>{const td=e.target.closest('td[data-row]');if(td){const frame=td.closest('.frame');selectCell(frame.dataset.frameId,+td.dataset.row,+td.dataset.col);syncPalettes();}});
$('#documentCanvas').addEventListener('input',e=>{const frame=e.target.closest('.frame-text');if(frame){const f=selectedFrame(doc);f.content.html=[...frame.childNodes].filter(n=>!n.className?.includes?.('frame-ui')&&!n.className?.includes?.('resize-handle')).map(n=>n.outerHTML||n.textContent).join('');touch(doc);}});
$$('[data-add-frame]').forEach(b=>b.onclick=()=>{const p=selectedPage(doc);const f=createFrame(b.dataset.addFrame,{zIndex:p.frames.length+1});p.frames.push(f);selectFrame(p.id,f.id);changed();});
$('[data-delete-frame]').onclick=()=>{const p=selectedPage(doc);p.frames=p.frames.filter(f=>f.id!==selection.frameId);selection.frameId=null;changed();};
$('[data-duplicate-frame]').onclick=()=>{const p=selectedPage(doc),f=selectedFrame(doc);if(!f)return;const copy=cloneDocument(f);copy.id=crypto.randomUUID();copy.x+=5;copy.y+=5;p.frames.push(copy);selectFrame(p.id,copy.id);changed();};
$$('[data-transform]').forEach(i=>i.oninput=()=>{const f=selectedFrame(doc);if(!f)return;const k=i.dataset.transform;f[k]=i.type==='checkbox'?i.checked:Number(i.value);changed();});
$$('[data-type-style]').forEach(i=>i.oninput=()=>{const f=selectedFrame(doc);if(f?.type!=='text')return;f.style[i.dataset.typeStyle]=i.type==='number'?Number(i.value):i.value;changed();});
$$('[data-table-action]').forEach(b=>b.onclick=()=>tableAction(b.dataset.tableAction));
function tableAction(a){const f=selectedFrame(doc);if(f?.type!=='table')return;const t=f.content;const cell=selection.cell||{row:0,col:0};if(a==='add-row')t.rows.push({id:crypto.randomUUID(),cells:t.columns.map(()=>({value:''}))});if(a==='delete-row')t.rows.splice(cell.row,1);if(a==='add-column'){t.columns.push({id:crypto.randomUUID(),width:25,label:'Column'});t.rows.forEach(r=>r.cells.push({value:''}));}if(a==='delete-column'){t.columns.splice(cell.col,1);t.rows.forEach(r=>r.cells.splice(cell.col,1));}if(a==='mark-subtotal')t.rows[cell.row].kind='subtotal';if(a==='clear-subtotal')delete t.rows[cell.row].kind;changed();}
$('#cellInput').oninput=()=>{const f=selectedFrame(doc),c=selection.cell;if(!f||!c)return;const cell=f.content.rows[c.row].cells[c.col];if($('#cellInput').value.startsWith('=')){cell.formula=$('#cellInput').value;delete cell.value;}else{cell.value=$('#cellInput').value;delete cell.formula;}changed();};
$('#discountType').onchange=$('#discountValue').oninput=()=>{const f=selectedFrame(doc);if(f?.type==='table'){f.content.discount={type:$('#discountType').value,value:Number($('#discountValue').value)||0};changed();}};
$('#carryLabel').oninput=()=>{const f=selectedFrame(doc);if(f?.type==='table'){f.content.carryLabel=$('#carryLabel').value;changed();}};
$('#addPage').onclick=()=>{const p=createPage();p.order=doc.pages.length;doc.pages.push(p);selectPage(p.id);changed();};
$('#duplicatePage').onclick=()=>{const p=cloneDocument(selectedPage(doc));p.id=crypto.randomUUID();p.frames.forEach(f=>f.id=crypto.randomUUID());doc.pages.push(p);selectPage(p.id);changed();};
$('#deletePage').onclick=()=>{if(doc.pages.length>1){doc.pages=doc.pages.filter(p=>p.id!==selection.pageId);selectPage(doc.pages[0].id);changed();}};
$('#newDocument').onclick=()=>{doc=createDocument();selection.pageId=doc.pages[0].id;refresh();};
$('#saveDocument').onclick=()=>{saveDocument(doc);$('#saveStatus').textContent='Saved';renderPages();};
$('#documentList').onchange=e=>{const loaded=loadDocument(e.target.value);if(loaded){doc=normalizeDocument(loaded);selection.pageId=doc.pages[0].id;refresh();}};
$('#exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));a.download=`${doc.title||'invoice'}.json`;a.click();};
$('#importJson').onchange=async e=>{const file=e.target.files[0];if(!file)return;const imported=normalizeDocument(JSON.parse(await file.text()));if(listDocuments().some(x=>x.id===imported.id))imported.id=crypto.randomUUID();doc=imported;selection.pageId=doc.pages[0].id;changed();};
$('#printDocument').onclick=()=>print();$('#togglePreview').onclick=()=>document.body.classList.toggle('mode-preview');
$$('.palette').forEach(p=>{p.querySelector('[data-collapse]').onclick=()=>p.classList.toggle('is-collapsed');let d;const h=p.querySelector('.palette-handle');h.onmousedown=e=>{if(e.target.closest('button'))return;d={x:e.clientX,y:e.clientY,l:p.offsetLeft,t:p.offsetTop};};window.addEventListener('mousemove',e=>{if(!d)return;p.style.left=d.l+e.clientX-d.x+'px';p.style.top=d.t+e.clientY-d.y+'px';p.style.right='auto';p.style.bottom='auto';});window.addEventListener('mouseup',()=>d=null);});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||document.activeElement.isContentEditable)return;if(e.key==='Delete')$('[data-delete-frame]').click();if(e.key==='p'&&(e.ctrlKey||e.metaKey)){e.preventDefault();print();}});
refresh();
